-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-04-07 10:37:34 CLT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE countries (
    countryid     VARCHAR2(4 CHAR) NOT NULL,
    country_name  VARCHAR2(150 CHAR),
    country_code  VARCHAR2(3 CHAR) NOT NULL,
    region        VARCHAR2(150 CHAR),
    income_group  VARCHAR2(50 CHAR)
);

ALTER TABLE countries ADD CONSTRAINT countries_pk PRIMARY KEY ( countryid );

CREATE TABLE indicator (
    countries_countryid   VARCHAR2(4 CHAR) NOT NULL,
    indicator_code        VARCHAR2(20 CHAR) NOT NULL,
    indicator_name        VARCHAR2(20 CHAR),
    source_note           VARCHAR2(255 CHAR),
    source_organization   VARCHAR2(500 CHAR),
    countries_countryid1  VARCHAR2(4 CHAR) NOT NULL
);

ALTER TABLE indicator ADD CONSTRAINT indicator_pk PRIMARY KEY ( countries_countryid );

CREATE TABLE poblation_year (
    p_ref         NUMBER(6) NOT NULL,
    country_code  VARCHAR2(4 CHAR) NOT NULL,
    year          NUMBER(4),
    poblations    NUMBER(15),
    p_ref1        NUMBER NOT NULL
);

ALTER TABLE poblation_year ADD CONSTRAINT poblation_year_pk PRIMARY KEY ( p_ref );

ALTER TABLE indicator
    ADD CONSTRAINT indicator_countries_fk FOREIGN KEY ( countries_countryid1 )
        REFERENCES countries ( countryid );

-- Error - Foreign Key Poblation_Year_Countries_FK has no columns



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             0
-- ALTER TABLE                              4
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
